name: 'Build Docker Image and Deploy to Cloud Run'

on:
  push:
    branches:
      - "main"

env:
  REGION: 'us-central1'
  SERVICE: 'boardgame-cloud-run'
  DOCKERHUB_USERNAME: 'rockslide'
  IMAGE_NAME: 'cloud-run-app'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/789248146868/locations/global/workloadIdentityPools/github-pool/providers/github-provider'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      # Docker Hub login
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and Push Container'
        run: |-
          IMAGE="${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'github-deployer@learning-cicd-457304.iam.gserviceaccount.com'


      - name: 'Deploy to Cloud Run'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
